---
abstract: 'Resize one rect in to another while preserving aspect ratio.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Test::Simple: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-FitRect
resources:
  bugtracker: https://github.com/bluefeet/Math-FitRect/issues
  repository: git://github.com/bluefeet/Math-FitRect.git
version: 0.04
